if &compatible
  set nocompatible
endif

set nobackup
set noswapfile
set noundofile
set nonumber
set autoread
set ignorecase
set showmatch
set smartcase
set ttyfast

set expandtab
set tabstop=2
set softtabstop=2
set shiftwidth=2

set list
set listchars=tab:>-,trail:-,nbsp:%,extends:>,precedes:<
set visualbell t_vb=
set backspace=indent,eol,start
set laststatus=0
set complete=.,w,b,u,k,i
set encoding=utf-8
set fileformats=unix,dos,mac
set clipboard^=unnamed,unnamedplus

filetype plugin indent on

