if &compatible
  set nocompatible
endif

set nobackup
set noswapfile
set noundofile

set ttyfast
set nonumber
set showmatch
set ignorecase
set smartcase
set autoread
set modeline

set visualbell t_vb=
set background=dark

set expandtab
set tabstop=2
set softtabstop=2
set shiftwidth=2

set list
set listchars=tab:>-,trail:-,nbsp:%,extends:>,precedes:<

set backspace=indent,eol,start
set laststatus=0
set complete=.,w,b,u,k,i
set encoding=utf-8
set fileformats=unix,dos,mac
set clipboard^=unnamed,unnamedplus

if has('packages')
  packadd! matchit
endif

if has("autocmd")
  filetype plugin indent on
endif

