set nobackup
set noswapfile

set autoread
set ruler
set showcmd
set showmatch
set ignorecase
set smartcase
set hidden
set hlsearch
set incsearch
set ttimeout
set ttimeoutlen=50
set scrolloff=4

set smarttab
set expandtab
set tabstop=2
set shiftwidth=0

set wildmenu
set wildmode=longest:full
set wildoptions=pum,fuzzy,tagfile
set shortmess=x
set list listchars=tab:>-,trail:-,nbsp:%,extends:>,precedes:<
set history=500
set laststatus=0
set encoding=utf-8
set fileformats=unix,dos
set clipboard^=unnamed,unnamedplus

filetype plugin indent on
